CREATE TABLE project (
  project_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  project_name TEXT NOT NULL,
  project_desc TEXT,
  client_name TEXT,
  client_company TEXT,
  client_email TEXT,
  client_phone NUMERIC,
  project_status TEXT NOT NULL,
  project_stack TEXT,
  max_members NUMERIC,
  date TIMESTAMPTZ DEFAULT now() NOT NULL
);