CREATE TABLE signup (
  signup_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  project_id  INTEGER REFERENCES project(project_id) ON DELETE CASCADE NOT NULL,
  signup_name TEXT,
  signup_github TEXT,
  signup_email TEXT
);