CREATE TABLE vote (
  vote_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  voter_email TEXT NOT NULL,
  project_id  INTEGER REFERENCES project(project_id) ON DELETE CASCADE NOT NULL,
  voter_name TEXT,
  voter_slack_name TEXT
);