export default {
  projects: [
    {
      project_id: 1,
      project_name: "Career Returnship App",
      project_desc:
        "This is a really long description for Project 1. Lorem ipsum dolor sit amet, sit illud posse porro at, ex has regione sententiae, adhuc habemus vis in. Eos id suas moderatius, in vero mutat omnesque sed, ex graeci fabulas ius. Aeque tation appellantur ad nec, cum reque congue te. Ei nec aeque dicunt, per te sale indoctum mnesarchum. Mea lucilius disputando cu.",
      client_name: "John Doe",
      client_email: "johndoe@gmail.com",
      client_company: "Doe Enterprises",
      client_phone: "3035551212",
      max_team_members: 5,
      status: "open vote",
      tech_stack: ["React", "Python"],
      sign_up: 0,
      vote: 0,
      date: "10/20/2020",
      table_vote: [
        {
          table_vote_id: 1,
          project_id: 1,
          voter_name: "Kathy",
          voter_slack_name: "CodeMeKathy",
          voter_email: "Kathy@aol.com",
        },
        {
          table_vote_id: 2,
          project_id: 1,
          voter_name: "Kim",
          voter_slack_name: "KimSlim",
          voter_email: "Kim@aol.com",
        },
      ],
      table_signup: [
        {
          signup_id: 1,
          project_id: 1,
          signup_name: "Kathy",
          signup_github_name: "CodeMeKathy",
          signup_email: "Kathy@aol.com",
        },
        {
          signup_id: 2,
          project_id: 1,
          signup_name: "Kim",
          signup_github_name: "KimSlim",
          signup_email: "Kim@aol.com",
        },
      ],
    },
    {
      project_id: 2,
      project_name: "ProjectHub App",
      project_desc:
        "This is a really long description for Project 2. Causae ornatus epicuri cu ius. Et nam purto deterruisset, quo mediocrem expetenda theophrastus ea. Usu in quod libris ocurreret, everti suscipit ex qui. In harum legimus repudiandae pro, qui ea alia elit maiorum, vix no soluta adolescens.",
      client_name: "Steve Madden",
      client_email: "steve_madden@gmail.com",
      client_company: "Doe Enterprises",
      client_phone: "3035551212",
      max_team_members: 5,
      status: "active",
      tech_stack: ["React", "PHP"],
      sign_up: 3,
      vote: 5,
      date: "10/20/2020",
      table_vote: [
        {
          table_vote_id: 1,
          project_id: 2,
          voter_name: "Kathy",
          voter_slack_name: "Kathy",
          voter_email: "Kathy@aol.com",
        },
        {
          table_vote_id: 2,
          project_id: 2,
          voter_name: "Kim",
          voter_slack_name: "Kim",
          voter_email: "Kim@aol.com",
        },
        {
          table_vote_id: 3,
          project_id: 2,
          voter_name: "Kathy",
          voter_slack_name: "Kathy",
          voter_email: "Kathy@aol.com",
        },
        {
          table_vote_id: 4,
          project_id: 2,
          voter_name: "Kim",
          voter_slack_name: "Kim",
          voter_email: "Kim@aol.com",
        },
        {
          table_vote_id: 5,
          project_id: 2,
          voter_name: "Kim",
          voter_slack_name: "Kim",
          voter_email: "Kim@aol.com",
        },
      ],
      table_signup: [
        {
          signup_id: 6,
          project_id: 2,
          signup_name: "Kathy",
          signup_github_name: "CodeMeKathy",
          signup_email: "Kathy@aol.com",
        },
        {
          signup_id: 7,
          project_id: 2,
          signup_name: "Kim",
          signup_github_name: "KimSlim",
          signup_email: "Kim@aol.com",
        },
      ],
    },
    {
      project_id: 3,
      project_name: "Delish App",
      project_desc:
        "This is a really long description for Project 3. Causae ornatus epicuri cu ius. Et nam purto deterruisset, quo mediocrem expetenda theophrastus ea. Usu in quod libris ocurreret, everti suscipit ex qui. In harum legimus repudiandae pro, qui ea alia elit maiorum, vix no soluta adolescens.",
      client_name: "Sally White",
      client_email: "sally_white@gmail.com",
      client_company: "Doe Enterprises",
      client_phone: "3035551212",
      max_team_members: 5,
      status: "open vote",
      tech_stack: ["COBOL", "CICS"],
      sign_up: 2,
      vote: 4,
      date: "10/20/2020",
      table_vote: [
        {
          table_vote_id: 1,
          project_id: 3,
          voter_name: "Kathy",
          voter_slack_name: "Kathy",
          voter_email: "Kathy@aol.com",
        },
        {
          table_vote_id: 2,
          project_id: 3,
          voter_name: "Kim",
          voter_slack_name: "Kim",
          voter_email: "Kim@aol.com",
        },
      ],
      table_signup: [
        {
          signup_id: 1,
          project_id: 3,
          signup_name: "Kathy",
          signup_github_name: "CodeMeKathy",
          signup_email: "Kathy@aol.com",
        },
        {
          signup_id: 2,
          project_id: 3,
          signup_name: "Kim",
          signup_github_name: "KimSlim",
          signup_email: "Kim@aol.com",
        },
      ],
    },
    {
      project_id: 4,
      project_name: "Special App",
      project_desc:
        "This is a really long description for Project 4. Causae ornatus epicuri cu ius. Et nam purto deterruisset, quo mediocrem expetenda theophrastus ea. Usu in quod libris ocurreret, everti suscipit ex qui. In harum legimus repudiandae pro, qui ea alia elit maiorum, vix no soluta adolescens.",
      client_name: "John Doe",
      client_email: "johndoe@gmail.com",
      client_company: "Doe Enterprises",
      client_phone: 3035551212,
      max_team_members: 5,
      status: "completed",
      tech_stack: ["COBOL", "CICS"],
      sign_up: 2,
      vote: 4,
      date: "10/20/2020",
      table_vote: [
        {
          table_vote_id: 1,
          project_id: 4,
          voter_name: "Kathy",
          voter_slack_name: "Kathy",
          voter_email: "Kathy@aol.com",
        },
        {
          table_vote_id: 2,
          project_id: 4,
          voter_name: "Kim",
          voter_slack_name: "Kim",
          voter_email: "Kim@aol.com",
        },
      ],
      table_signup: [
        {
          signup_id: 1,
          project_id: 4,
          signup_name: "Kathy",
          signup_github_name: "CodeMeKathy",
          signup_email: "Kathy@aol.com",
        },
        {
          signup_id: 2,
          project_id: 4,
          signup_name: "Kim",
          signup_github_name: "KimSlim",
          signup_email: "Kim@aol.com",
        },
      ],
    },
    {
      project_id: 5,
      project_name: "New Project 5",
      project_desc:
        "This is a really long description for Project 5. Causae ornatus epicuri cu ius. Et nam purto deterruisset, quo mediocrem expetenda theophrastus ea. Usu in quod libris ocurreret, everti suscipit ex qui. In harum legimus repudiandae pro, qui ea alia elit maiorum, vix no soluta adolescens.",
      client_name: "John Doe",
      client_email: "johndoe@gmail.com",
      client_company: "Doe Enterprises",
      client_phone: 3035551212,
      max_team_members: 5,
      status: "sign up",
      tech_stack: ["React", "Python"],
      sign_up: 2,
      vote: 4,
      date: "10/20/2020",
      table_vote: [
        {
          table_vote_id: 1,
          project_id: 5,
          voter_name: "Kathy",
          voter_slack_name: "Kathy",
          voter_email: "Kathy@aol.com",
        },
        {
          table_vote_id: 2,
          project_id: 5,
          voter_name: "Kim",
          voter_slack_name: "Kim",
          voter_email: "Kim@aol.com",
        },
      ],
      table_signup: [
        {
          signup_id: 1,
          project_id: 5,
          signup_name: "Kathy",
          signup_github_name: "CodeMeKathy",
          signup_email: "Kathy@aol.com",
        },
        {
          signup_id: 2,
          project_id: 5,
          signup_name: "Kim",
          signup_github_name: "KimSlim",
          signup_email: "Kim@aol.com",
        },
      ],
    },
    {
      project_id: 6,
      project_name: "New Project 6",
      project_desc:
        "This is a really long description for Project 6. Causae ornatus epicuri cu ius. Et nam purto deterruisset, quo mediocrem expetenda theophrastus ea. Usu in quod libris ocurreret, everti suscipit ex qui. In harum legimus repudiandae pro, qui ea alia elit maiorum, vix no soluta adolescens.",
      client_name: "John Doe",
      client_email: "johndoe@gmail.com",
      client_company: "Doe Enterprises",
      client_phone: 3035551212,
      max_team_members: 5,
      status: "sign up",
      tech_stack: ["React", "Python"],
      sign_up: 2,
      vote: 4,
      date: "10/20/2020",
      table_vote: [
        {
          table_vote_id: 1,
          project_id: 6,
          voter_name: "Kathy",
          voter_slack_name: "Kathy",
          voter_email: "Kathy@aol.com",
        },
        {
          table_vote_id: 2,
          project_id: 6,
          voter_name: "Kim",
          voter_slack_name: "Kim",
          voter_email: "Kim@aol.com",
        },
      ],
      table_signup: [
        {
          signup_id: 1,
          project_id: 6,
          signup_name: "Kathy",
          signup_github_name: "CodeMeKathy",
          signup_email: "Kathy@aol.com",
        },
        {
          signup_id: 2,
          project_id: 6,
          signup_name: "Kim",
          signup_github_name: "KimSlim",
          signup_email: "Kim@aol.com",
        },
      ],
    },
    {
      project_id: 7,
      project_name: "New Project 7",
      project_desc:
        "This is a really long description for Project 7. Causae ornatus epicuri cu ius. Et nam purto deterruisset, quo mediocrem expetenda theophrastus ea. Usu in quod libris ocurreret, everti suscipit ex qui. In harum legimus repudiandae pro, qui ea alia elit maiorum, vix no soluta adolescens.",
      client_name: "John Doe",
      client_email: "johndoe@gmail.com",
      client_company: "Doe Enterprises",
      client_phone: 3035551212,
      max_team_members: 5,
      status: "sign up",
      tech_stack: ["React", "Python"],
      sign_up: 2,
      vote: 4,
      date: "10/20/2020",
      table_vote: [
        {
          table_vote_id: 1,
          project_id: 7,
          voter_name: "Kathy",
          voter_slack_name: "Kathy",
          voter_email: "Kathy@aol.com",
        },
        {
          table_vote_id: 2,
          project_id: 7,
          voter_name: "Kim",
          voter_slack_name: "Kim",
          voter_email: "Kim@aol.com",
        },
      ],
      table_signup: [
        {
          signup_id: 1,
          project_id: 7,
          signup_name: "Kathy",
          signup_github_name: "CodeMeKathy",
          signup_email: "Kathy@aol.com",
        },
        {
          signup_id: 2,
          project_id: 7,
          signup_name: "Kim",
          signup_github_name: "KimSlim",
          signup_email: "Kim@aol.com",
        },
      ],
    },
    {
      project_id: 8,
      project_name: "New Project 8",
      project_desc:
        "This is a really long description for Project 8. Causae ornatus epicuri cu ius. Et nam purto deterruisset, quo mediocrem expetenda theophrastus ea. Usu in quod libris ocurreret, everti suscipit ex qui. In harum legimus repudiandae pro, qui ea alia elit maiorum, vix no soluta adolescens.",
      client_name: "John Doe",
      client_email: "johndoe@gmail.com",
      client_company: "Doe Enterprises",
      client_phone: 3035551212,
      max_team_members: 5,
      status: "open vote",
      tech_stack: ["COBOL", "CICS"],
      sign_up: 2,
      vote: 4,
      date: "10/20/2020",
      table_vote: [
        {
          table_vote_id: 1,
          project_id: 8,
          voter_name: "Kathy",
          voter_slack_name: "Kathy",
          voter_email: "Kathy@aol.com",
        },
        {
          table_vote_id: 2,
          project_id: 8,
          voter_name: "Kim",
          voter_slack_name: "Kim",
          voter_email: "Kim@aol.com",
        },
      ],
      table_signup: [
        {
          signup_id: 1,
          project_id: 8,
          signup_name: "Kathy",
          signup_github_name: "CodeMeKathy",
          signup_email: "Kathy@aol.com",
        },
        {
          signup_id: 2,
          project_id: 8,
          signup_name: "Kim",
          signup_github_name: "KimSlim",
          signup_email: "Kim@aol.com",
        },
      ],
    },
    {
      project_id: 9,
      project_name: "New Project 9",
      project_desc:
        "This is a really long description for Project 9. Causae ornatus epicuri cu ius. Et nam purto deterruisset, quo mediocrem expetenda theophrastus ea. Usu in quod libris ocurreret, everti suscipit ex qui. In harum legimus repudiandae pro, qui ea alia elit maiorum, vix no soluta adolescens.",
      client_name: "John Doe",
      client_email: "johndoe@gmail.com",
      client_company: "Doe Enterprises",
      client_phone: 3035551212,
      max_team_members: 5,
      status: "open vote",
      tech_stack: ["COBOL", "CICS"],
      sign_up: 2,
      vote: 4,
      date: "10/20/2020",
      table_vote: [
        {
          table_vote_id: 1,
          project_id: 9,
          voter_name: "Kathy",
          voter_slack_name: "Kathy",
          voter_email: "Kathy@aol.com",
        },
        {
          table_vote_id: 2,
          project_id: 9,
          voter_name: "Kim",
          voter_slack_name: "Kim",
          voter_email: "Kim@aol.com",
        },
      ],
      table_signup: [
        {
          signup_id: 1,
          project_id: 9,
          signup_name: "Kathy",
          signup_github_name: "CodeMeKathy",
          signup_email: "Kathy@aol.com",
        },
        {
          signup_id: 2,
          project_id: 9,
          signup_name: "Kim",
          signup_github_name: "KimSlim",
          signup_email: "Kim@aol.com",
        },
      ],
    },
    {
      project_id: 10,
      project_name: "New Project 10",
      project_desc:
        "This is a really long description for Project 10. Causae ornatus epicuri cu ius. Et nam purto deterruisset, quo mediocrem expetenda theophrastus ea. Usu in quod libris ocurreret, everti suscipit ex qui. In harum legimus repudiandae pro, qui ea alia elit maiorum, vix no soluta adolescens.",
      client_name: "John Doe",
      client_email: "johndoe@gmail.com",
      client_company: "Doe Enterprises",
      client_phone: 3035551212,
      max_team_members: 5,
      status: "open vote",
      tech_stack: ["COBOL", "CICS"],
      sign_up: 2,
      vote: 4,
      date: "10/20/2020",
      table_vote: [
        {
          table_vote_id: 1,
          project_id: 10,
          voter_name: "Kathy",
          voter_slack_name: "Kathy",
          voter_email: "Kathy@aol.com",
        },
        {
          table_vote_id: 2,
          project_id: 10,
          voter_name: "Kim",
          voter_slack_name: "Kim",
          voter_email: "Kim@aol.com",
        },
      ],
      table_signup: [
        {
          signup_id: 1,
          project_id: 10,
          signup_name: "Kathy",
          signup_github_name: "CodeMeKathy",
          signup_email: "Kathy@aol.com",
        },
        {
          signup_id: 2,
          project_id: 10,
          signup_name: "Kim",
          signup_github_name: "KimSlim",
          signup_email: "Kim@aol.com",
        },
      ],
    },
  ],
};
