export default {
  Project: [
    {
      project_id: 1,
      project_name: "Wildlife Researcher Observation App",
      project_desc: "Currently dead project",
      project_status: "Complete",
      project_stack: "Python,React,PostgreSQL",
      max_members: 10,
      date: new Date(),
      client_name: "Henry Diggins",
      client_email: "",
      client_phone: "",
    },
    {
      project_id: 2,
      project_name: "Menu Planning Spinner",
      project_desc: "Spin to see what you will eat tonight",
      project_status: "OpenVote",
      project_stack: "Python,React,PostgreSQL",
      max_members: 10,
      date: new Date(),
      client_name: "Mary Tester",
      client_email: "",
      client_phone: "",
    },
    {
      project_id: 3,
      project_name: "Good Habits App",
      project_desc: "Who knows what this is",
      project_status: "SignUp",
      project_stack: "Python, React, PostgreSQL",
      max_members: 10,
      date: new Date(),
      client_name: "Bob Dylan",
      client_email: "",
      client_phone: "",
    },
    {
      project_id: 4,
      project_name: "Another Dumb App",
      project_desc: "Who knows what this is",
      project_status: "Active",
      project_stack: "Python, React, PostgreSQL",
      max_members: 10,
      date: new Date(),
      client_name: "",
      client_email: "",
      client_phone: "",
    },
    {
      project_id: 5,
      project_name: "Project 5",
      project_desc: "Currently dead project",
      project_status: "Complete",
      project_stack: "Python,React,PostgreSQL",
      max_members: 10,
      date: new Date(),
      client_name: "Henry Diggins",
      client_email: "",
      client_phone: "",
    },
    {
      project_id: 6,
      project_name: "Project 6",
      project_desc: "Spin to see what you will eat tonight",
      project_status: "OpenVote",
      project_stack: "Python,React,PostgreSQL",
      max_members: 10,
      date: new Date(),
      client_name: "Mary Tester",
      client_email: "",
      client_phone: "",
    },
    {
      project_id: 7,
      project_name: "Project 7",
      project_desc: "Who knows what this is",
      project_status: "SignUp",
      project_stack: "Python, React, PostgreSQL",
      max_members: 10,
      date: new Date(),
      client_name: "Bob Dylan",
      client_email: "",
      client_phone: "",
    },
    {
      project_id: 8,
      project_name: "Project 8",
      project_desc: "Who knows what this is",
      project_status: "Active",
      project_stack: "Python, React, PostgreSQL",
      max_members: 10,
      date: new Date(),
      client_name: "",
      client_email: "",
      client_phone: "",
    },
    {
      project_id: 9,
      project_name: "Project 9",
      project_desc: "Currently dead project",
      project_status: "Complete",
      project_stack: "Python,React,PostgreSQL",
      max_members: 10,
      date: new Date(),
      client_name: "Henry Diggins",
      client_email: "",
      client_phone: "",
    },
    {
      project_id: 10,
      project_name: "Project 10",
      project_desc: "Spin to see what you will eat tonight",
      project_status: "OpenVote",
      project_stack: "Python,React,PostgreSQL",
      max_members: 10,
      date: new Date(),
      client_name: "Mary Tester",
      client_email: "",
      client_phone: "",
    },
    {
      project_id: 11,
      project_name: "Project 11",
      project_desc: "Who knows what this is",
      project_status: "SignUp",
      project_stack: "Python, React, PostgreSQL",
      max_members: 10,
      date: new Date(),
      client_name: "Bob Dylan",
      client_email: "",
      client_phone: "",
    },
    {
      project_id: 12,
      project_name: "Project 12",
      project_desc: "Who knows what this is",
      project_status: "Active",
      project_stack: "Python, React, PostgreSQL",
      max_members: 10,
      date: new Date(),
      client_name: "",
      client_email: "",
      client_phone: "",
    },
  ],
  Signup: [
    {
      signup_id: 1,
      project_id: 1,
      signup_name: "",
      signup_email: "",
      signup_github: "",
    },
  ],
  Vote: [
    {
      voter_id: 1,
      project_id: 1,
      voter_name: "",
      voter_email: "",
      voter_slack_name: "",
    },
  ],
};
